version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-feed-mail-sender
    depends_on:
      - postgres
      - kafka
    environment:
      DB_HOST: stock-feed-mail-sender-postgres:5432
      KAFKA_SERVERS: kafka:9092
    ports:
      - "9010:9010"
    networks:
      - stock-feed-mail-sender-network
      - stock-feed-kafka-network

  postgres:
    image: postgres:latest
    container_name: stock-feed-mail-sender-postgres
    environment:
      POSTGRES_DB: stock_feed_kafka_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stock-feed-mail-sender-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
    networks:
      - stock-feed-kafka-network
      - kafka-network

volumes:
  postgres_data:
  kafka_data:

networks:
  kafka-network:
    driver: bridge
  stock-feed-mail-sender-network:
  stock-feed-kafka-network:
    external: true
