spring:

  kafka:
    template:
      default-topic: stock-feed-topic
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
